debug: true

ssl: false

signature: false

sentry:
  active: false

server:
  port: 8080

db:
  dialect: postgres
  host: localhost
  port: 8432
  username: postgres
  password: password
  dbname: postgres
  sslMode: disable
  logMode: true
