debug: false

ssl: false

signature: false

sentry:
  active: false

server:
  port: 8082

db:
  dialect: postgres
  host: localhost
  port: 8432
  username: postgres
  password: password
  dbname: postgres
  sslMode: disable
  logMode: true

Networks:
  - name: mainnet
    host: localhost
    port: 8332
    username: username
    password: password
    passphrase: passphrase
  - name: testnet
    host: localhost
    port: 8332
    username: username
    password: password
    passphrase: passphrase