debug: true

ssl: false

signature: false

sentry:
  active: false

server:
  port: 8080

db:
  dialect: postgres
  host: localhost
  port: 54321
  username: postgres
  password: password
  dbname: postgres
  sslMode: disable
  logMode: true

Networks:
  - name: mainnet
    host: localhost
    port: 8332
    username: user
    password: password
    passphrase: passphrase
  - name: testnet
    host: localhost
    port: 8332
    username: username
    password: password
    passphrase: passphrase
